name: sync_webdriver
version: 2.0.0-pre.1
author: Marc Fisher II <fisherii@google.com>
description: >
  Provides WebDriver bindings for Dart. These use the WebDriver JSON interface,
  and as such, require the use of the WebDriver remote server.
homepage: https://github.com/google/dart-sync-webdriver
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  matcher: '^0.12.0+1'
  stack_trace: '^1.3.2'
  sync_socket: '^1.0.2+1'
  unittest: '^0.11.6+1'
dev_dependencies:
  path: '^1.3.5'
  test: '^0.12.2'
